import type { Customer } from "./types"

export const customers: Customer[] = [
  {
    id: "C1001",
    name: "John Smith",
    age: 35,
    location: "New York, NY",
    profilePhoto: "/placeholder.svg?height=200&width=200",
    priority: "high",
    creditScore: 780,
    totalAssets: 850000,
    totalLiabilities: 320000,
    spendingVsIncome: [
      { month: "Jan", income: 12000, spending: 8500 },
      { month: "Feb", income: 12000, spending: 9200 },
      { month: "Mar", income: 12500, spending: 8800 },
      { month: "Apr", income: 12500, spending: 9500 },
      { month: "May", income: 13000, spending: 9800 },
      { month: "Jun", income: 13000, spending: 9200 },
    ],
    loanHistory: {
      totalTaken: 450000,
      totalRepaid: 130000,
      totalOutstanding: 320000,
      emiPaymentHistory: [
        { month: "Jan", onTime: true },
        { month: "Feb", onTime: true },
        { month: "Mar", onTime: true },
        { month: "Apr", onTime: true },
        { month: "May", onTime: true },
        { month: "Jun", onTime: true },
      ],
    },
    creditCardUtilization: {
      "Premium Card": 45,
      "Travel Card": 30,
      "Cashback Card": 15,
      "Business Card": 10,
    },
    spendingPatterns: {
        byCategory: {
            Housing: 3500,
            Transportation: 1200,
            Food: 1500,
            Entertainment: 800,
            Shopping: 1000,
            Utilities: 600,
            Healthcare: 400,
        },
        monthlyExpenditure: [
            { month: "Jan", amount: 8500 },
            { month: "Feb", amount: 9200 },
            { month: "Mar", amount: 8800 },
            { month: "Apr", amount: 9500 },
            { month: "May", amount: 9800 },
            { month: "Jun", amount: 9200 },
        ],
        recurringPayments: [
            { service: "Mortgage", category: "Housing", frequency: "Monthly", amount: 2500 },
            { service: "Netflix", category: "Entertainment", frequency: "Monthly", amount: 15 },
            { service: "Gym Membership", category: "Health", frequency: "Monthly", amount: 80 },
            { service: "Car Insurance", category: "Transportation", frequency: "Monthly", amount: 150 },
            { service: "Internet", category: "Utilities", frequency: "Monthly", amount: 80 },
        ],
        monthly: []
    },
    transactions: [
      {
        id: "T1001",
        date: "2023-06-28",
        description: "Grocery Shopping",
        merchant: "Whole Foods",
        category: "Food",
        amount: 125,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T1002",
        date: "2023-06-25",
        description: "Monthly Salary",
        merchant: "ABC Corp",
        category: "Income",
        amount: 13000,
        type: "credit",
        isAnomalous: false,
      },
      {
        id: "T1003",
        date: "2023-06-22",
        description: "Restaurant Dinner",
        merchant: "Le Bernardin",
        category: "Food",
        amount: 350,
        type: "debit",
        isAnomalous: true,
      },
      {
        id: "T1004",
        date: "2023-06-20",
        description: "Mortgage Payment",
        merchant: "Chase Bank",
        category: "Housing",
        amount: 2500,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T1005",
        date: "2023-06-18",
        description: "Online Shopping",
        merchant: "Amazon",
        category: "Shopping",
        amount: 210,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T1006",
        date: "2023-06-15",
        description: "Utility Bill",
        merchant: "ConEd",
        category: "Utilities",
        amount: 180,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T1007",
        date: "2023-06-12",
        description: "Investment Dividend",
        merchant: "Vanguard",
        category: "Income",
        amount: 450,
        type: "credit",
        isAnomalous: false,
      },
      {
        id: "T1008",
        date: "2023-06-10",
        description: "Car Payment",
        merchant: "Toyota Financial",
        category: "Transportation",
        amount: 450,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T1009",
        date: "2023-06-08",
        description: "Healthcare Premium",
        merchant: "Blue Cross",
        category: "Healthcare",
        amount: 320,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T1010",
        date: "2023-06-05",
        description: "Electronics Purchase",
        merchant: "Best Buy",
        category: "Shopping",
        amount: 1200,
        type: "debit",
        isAnomalous: true,
      },
    ],
    anomalies: [
      "Unusually high restaurant expense of $350 at Le Bernardin on June 22",
      "Large electronics purchase of $1,200 at Best Buy on June 5",
    ],
    aiInsights: {
      financialHealthScore: 85,
      investmentSuggestions: [
        {
          name: "Diversified ETF Portfolio",
          description: "Low-cost ETFs across multiple sectors for long-term growth",
          riskLevel: "Moderate",
          expectedReturn: 8.5,
          minInvestment: 5000,
        },
        {
          name: "Real Estate Investment Trust",
          description: "Income-generating real estate portfolio with quarterly dividends",
          riskLevel: "Moderate-Low",
          expectedReturn: 6.2,
          minInvestment: 10000,
        },
        {
          name: "Tech Growth Fund",
          description: "High-growth technology companies with strong future potential",
          riskLevel: "High",
          expectedReturn: 12.5,
          minInvestment: 7500,
        },
      ],
      loanRecommendations: [
        {
          type: "Home Equity Line of Credit",
          description: "Access your home equity with flexible withdrawal options",
          amount: 150000,
          interestRate: 4.5,
          term: "15 years",
          emi: 1150,
        },
        {
          type: "Personal Loan",
          description: "Consolidate high-interest debt or fund major expenses",
          amount: 25000,
          interestRate: 7.2,
          term: "5 years",
          emi: 498,
        },
      ],
      debtRepaymentPlan: {
        currentPlan: [
          { month: "Jul", amount: 3100 },
          { month: "Aug", amount: 3100 },
          { month: "Sep", amount: 3100 },
          { month: "Oct", amount: 3100 },
          { month: "Nov", amount: 3100 },
          { month: "Dec", amount: 3100 },
        ],
        optimizedPlan: [
          { month: "Jul", amount: 3500 },
          { month: "Aug", amount: 3500 },
          { month: "Sep", amount: 3500 },
          { month: "Oct", amount: 2800 },
          { month: "Nov", amount: 2800 },
          { month: "Dec", amount: 2800 },
        ],
        totalSavings: 12500,
      },
      upcomingPayments: [
        {
          description: "Mortgage Payment",
          dueDate: "July 5, 2023",
          amount: 2500,
          isOverdue: false,
        },
        {
          description: "Car Loan",
          dueDate: "July 10, 2023",
          amount: 450,
          isOverdue: false,
        },
        {
          description: "Credit Card Bill",
          dueDate: "June 30, 2023",
          amount: 1850,
          isOverdue: true,
        },
      ],
    },
  },
  {
    id: "C1002",
    name: "Sarah Johnson",
    age: 42,
    location: "Chicago, IL",
    profilePhoto: "/placeholder.svg?height=200&width=200",
    priority: "medium",
    creditScore: 720,
    totalAssets: 420000,
    totalLiabilities: 210000,
    spendingVsIncome: [
      { month: "Jan", income: 8500, spending: 7200 },
      { month: "Feb", income: 8500, spending: 7500 },
      { month: "Mar", income: 8500, spending: 7800 },
      { month: "Apr", income: 9000, spending: 7600 },
      { month: "May", income: 9000, spending: 8200 },
      { month: "Jun", income: 9000, spending: 8500 },
    ],
    loanHistory: {
      totalTaken: 280000,
      totalRepaid: 70000,
      totalOutstanding: 210000,
      emiPaymentHistory: [
        { month: "Jan", onTime: true },
        { month: "Feb", onTime: true },
        { month: "Mar", onTime: false },
        { month: "Apr", onTime: true },
        { month: "May", onTime: true },
        { month: "Jun", onTime: false },
      ],
    },
    creditCardUtilization: {
      "Rewards Card": 60,
      "Shopping Card": 25,
      "Travel Card": 15,
    },
    spendingPatterns: {
        byCategory: {
            Housing: 2200,
            Transportation: 800,
            Food: 1100,
            Entertainment: 600,
            Shopping: 1500,
            Utilities: 500,
            Healthcare: 300,
        },
        monthlyExpenditure: [
            { month: "Jan", amount: 7200 },
            { month: "Feb", amount: 7500 },
            { month: "Mar", amount: 7800 },
            { month: "Apr", amount: 7600 },
            { month: "May", amount: 8200 },
            { month: "Jun", amount: 8500 },
        ],
        recurringPayments: [
            { service: "Rent", category: "Housing", frequency: "Monthly", amount: 2200 },
            { service: "Car Payment", category: "Transportation", frequency: "Monthly", amount: 350 },
            { service: "Hulu", category: "Entertainment", frequency: "Monthly", amount: 12 },
            { service: "Disney+", category: "Entertainment", frequency: "Monthly", amount: 8 },
            { service: "Cell Phone", category: "Utilities", frequency: "Monthly", amount: 95 },
        ],
        monthly: []
    },
    transactions: [
      {
        id: "T2001",
        date: "2023-06-28",
        description: "Grocery Shopping",
        merchant: "Trader Joe's",
        category: "Food",
        amount: 95,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T2002",
        date: "2023-06-25",
        description: "Monthly Salary",
        merchant: "XYZ Inc",
        category: "Income",
        amount: 9000,
        type: "credit",
        isAnomalous: false,
      },
      {
        id: "T2003",
        date: "2023-06-22",
        description: "Shopping Spree",
        merchant: "Nordstrom",
        category: "Shopping",
        amount: 850,
        type: "debit",
        isAnomalous: true,
      },
      {
        id: "T2004",
        date: "2023-06-20",
        description: "Rent Payment",
        merchant: "Property Management",
        category: "Housing",
        amount: 2200,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T2005",
        date: "2023-06-18",
        description: "Dining Out",
        merchant: "Cheesecake Factory",
        category: "Food",
        amount: 120,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T2006",
        date: "2023-06-15",
        description: "Utility Bill",
        merchant: "ComEd",
        category: "Utilities",
        amount: 140,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T2007",
        date: "2023-06-12",
        description: "Bonus Payment",
        merchant: "XYZ Inc",
        category: "Income",
        amount: 1500,
        type: "credit",
        isAnomalous: false,
      },
      {
        id: "T2008",
        date: "2023-06-10",
        description: "Car Payment",
        merchant: "Honda Financial",
        category: "Transportation",
        amount: 350,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T2009",
        date: "2023-06-08",
        description: "Healthcare Visit",
        merchant: "City Medical Center",
        category: "Healthcare",
        amount: 150,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T2010",
        date: "2023-06-05",
        description: "Online Shopping",
        merchant: "Amazon",
        category: "Shopping",
        amount: 220,
        type: "debit",
        isAnomalous: false,
      },
    ],
    anomalies: ["Large shopping expense of $850 at Nordstrom on June 22"],
    aiInsights: {
      financialHealthScore: 68,
      investmentSuggestions: [
        {
          name: "Balanced Mutual Fund",
          description: "Mix of stocks and bonds for moderate growth with reduced volatility",
          riskLevel: "Moderate",
          expectedReturn: 7.0,
          minInvestment: 3000,
        },
        {
          name: "Dividend Stock Portfolio",
          description: "Stable companies with history of consistent dividend payments",
          riskLevel: "Moderate-Low",
          expectedReturn: 5.5,
          minInvestment: 5000,
        },
      ],
      loanRecommendations: [
        {
          type: "Debt Consolidation Loan",
          description: "Combine high-interest debts into a single lower-rate loan",
          amount: 15000,
          interestRate: 8.5,
          term: "3 years",
          emi: 472,
        },
      ],
      debtRepaymentPlan: {
        currentPlan: [
          { month: "Jul", amount: 2200 },
          { month: "Aug", amount: 2200 },
          { month: "Sep", amount: 2200 },
          { month: "Oct", amount: 2200 },
          { month: "Nov", amount: 2200 },
          { month: "Dec", amount: 2200 },
        ],
        optimizedPlan: [
          { month: "Jul", amount: 2500 },
          { month: "Aug", amount: 2500 },
          { month: "Sep", amount: 2500 },
          { month: "Oct", amount: 2000 },
          { month: "Nov", amount: 2000 },
          { month: "Dec", amount: 1800 },
        ],
        totalSavings: 6800,
      },
      upcomingPayments: [
        {
          description: "Rent Payment",
          dueDate: "July 1, 2023",
          amount: 2200,
          isOverdue: false,
        },
        {
          description: "Car Loan",
          dueDate: "July 10, 2023",
          amount: 350,
          isOverdue: false,
        },
        {
          description: "Credit Card Bill",
          dueDate: "June 28, 2023",
          amount: 1250,
          isOverdue: true,
        },
      ],
    },
  },
  {
    id: "C1003",
    name: "Michael Chen",
    age: 29,
    location: "San Francisco, CA",
    profilePhoto: "/placeholder.svg?height=200&width=200",
    priority: "low",
    creditScore: 650,
    totalAssets: 120000,
    totalLiabilities: 85000,
    spendingVsIncome: [
      { month: "Jan", income: 7500, spending: 7200 },
      { month: "Feb", income: 7500, spending: 7400 },
      { month: "Mar", income: 7500, spending: 7600 },
      { month: "Apr", income: 7800, spending: 7500 },
      { month: "May", income: 7800, spending: 7900 },
      { month: "Jun", income: 7800, spending: 7700 },
    ],
    loanHistory: {
      totalTaken: 95000,
      totalRepaid: 10000,
      totalOutstanding: 85000,
      emiPaymentHistory: [
        { month: "Jan", onTime: true },
        { month: "Feb", onTime: false },
        { month: "Mar", onTime: false },
        { month: "Apr", onTime: true },
        { month: "May", onTime: false },
        { month: "Jun", onTime: true },
      ],
    },
    creditCardUtilization: {
      "Basic Card": 85,
      "Student Card": 70,
    },
    spendingPatterns: {
        byCategory: {
            Housing: 2800,
            Transportation: 500,
            Food: 1200,
            Entertainment: 800,
            Shopping: 900,
            Utilities: 400,
            Healthcare: 200,
        },
        monthlyExpenditure: [
            { month: "Jan", amount: 7200 },
            { month: "Feb", amount: 7400 },
            { month: "Mar", amount: 7600 },
            { month: "Apr", amount: 7500 },
            { month: "May", amount: 7900 },
            { month: "Jun", amount: 7700 },
        ],
        recurringPayments: [
            { service: "Rent", category: "Housing", frequency: "Monthly", amount: 2800 },
            { service: "Student Loan", category: "Debt", frequency: "Monthly", amount: 450 },
            { service: "Netflix", category: "Entertainment", frequency: "Monthly", amount: 15 },
            { service: "Spotify", category: "Entertainment", frequency: "Monthly", amount: 10 },
            { service: "Gym Membership", category: "Health", frequency: "Monthly", amount: 65 },
        ],
        monthly: []
    },
    transactions: [
      {
        id: "T3001",
        date: "2023-06-28",
        description: "Grocery Shopping",
        merchant: "Safeway",
        category: "Food",
        amount: 110,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T3002",
        date: "2023-06-25",
        description: "Monthly Salary",
        merchant: "Tech Startup Inc",
        category: "Income",
        amount: 7800,
        type: "credit",
        isAnomalous: false,
      },
      {
        id: "T3003",
        date: "2023-06-22",
        description: "Bar Tab",
        merchant: "Cityscape Lounge",
        category: "Entertainment",
        amount: 180,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T3004",
        date: "2023-06-20",
        description: "Rent Payment",
        merchant: "Urban Properties",
        category: "Housing",
        amount: 2800,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T3005",
        date: "2023-06-18",
        description: "Electronics Purchase",
        merchant: "Apple Store",
        category: "Shopping",
        amount: 1200,
        type: "debit",
        isAnomalous: true,
      },
      {
        id: "T3006",
        date: "2023-06-15",
        description: "Utility Bill",
        merchant: "PG&E",
        category: "Utilities",
        amount: 120,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T3007",
        date: "2023-06-12",
        description: "Freelance Payment",
        merchant: "Freelance Client",
        category: "Income",
        amount: 800,
        type: "credit",
        isAnomalous: false,
      },
      {
        id: "T3008",
        date: "2023-06-10",
        description: "Student Loan Payment",
        merchant: "Navient",
        category: "Debt",
        amount: 450,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T3009",
        date: "2023-06-08",
        description: "Dining Out",
        merchant: "Sushi Place",
        category: "Food",
        amount: 85,
        type: "debit",
        isAnomalous: false,
      },
      {
        id: "T3010",
        date: "2023-06-05",
        description: "Transportation",
        merchant: "Uber",
        category: "Transportation",
        amount: 45,
        type: "debit",
        isAnomalous: false,
      },
    ],
    anomalies: [
      "High-value electronics purchase of $1,200 at Apple Store on June 18",
      "Consistently high credit card utilization (85% and 70%)",
    ],
    aiInsights: {
      financialHealthScore: 42,
      investmentSuggestions: [
        {
          name: "Emergency Fund Builder",
          description: "High-yield savings account to build 3-6 months of expenses",
          riskLevel: "Low",
          expectedReturn: 3.5,
          minInvestment: 500,
        },
        {
          name: "Micro-Investment Plan",
          description: "Small regular investments in diversified ETFs",
          riskLevel: "Low-Moderate",
          expectedReturn: 5.0,
          minInvestment: 100,
        },
      ],
      loanRecommendations: [
        {
          type: "Credit Card Refinancing",
          description: "Lower interest rate to help pay down high-interest credit card debt",
          amount: 8000,
          interestRate: 12.5,
          term: "2 years",
          emi: 380,
        },
      ],
      debtRepaymentPlan: {
        currentPlan: [
          { month: "Jul", amount: 1200 },
          { month: "Aug", amount: 1200 },
          { month: "Sep", amount: 1200 },
          { month: "Oct", amount: 1200 },
          { month: "Nov", amount: 1200 },
          { month: "Dec", amount: 1200 },
        ],
        optimizedPlan: [
          { month: "Jul", amount: 1500 },
          { month: "Aug", amount: 1500 },
          { month: "Sep", amount: 1500 },
          { month: "Oct", amount: 1000 },
          { month: "Nov", amount: 1000 },
          { month: "Dec", amount: 800 },
        ],
        totalSavings: 3800,
      },
      upcomingPayments: [
        {
          description: "Rent Payment",
          dueDate: "July 1, 2023",
          amount: 2800,
          isOverdue: false,
        },
        {
          description: "Student Loan",
          dueDate: "July 10, 2023",
          amount: 450,
          isOverdue: false,
        },
        {
          description: "Credit Card Minimum",
          dueDate: "June 25, 2023",
          amount: 350,
          isOverdue: true,
        },
      ],
    },
  },
]

