// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu4B7asXaYNaxUF4qm8jS313SzvTL_-oE',
    appId: '1:367467653808:web:94acb3e7ef93114c046975',
    messagingSenderId: '367467653808',
    projectId: 'vyom-notification',
    authDomain: 'vyom-notification.firebaseapp.com',
    storageBucket: 'vyom-notification.firebasestorage.app',
    measurementId: 'G-RRT6R2N0GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW19uL_CmEq9-1pQi8q3s3-gw_cmCvxVk',
    appId: '1:367467653808:android:8fba1e5d23e29b62046975',
    messagingSenderId: '367467653808',
    projectId: 'vyom-notification',
    storageBucket: 'vyom-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAydNlI6Pu551aHogBZast7KUJ3vKLWpgc',
    appId: '1:367467653808:ios:00f356faf06eb791046975',
    messagingSenderId: '367467653808',
    projectId: 'vyom-notification',
    storageBucket: 'vyom-notification.firebasestorage.app',
    iosBundleId: 'com.example.vyom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAydNlI6Pu551aHogBZast7KUJ3vKLWpgc',
    appId: '1:367467653808:ios:00f356faf06eb791046975',
    messagingSenderId: '367467653808',
    projectId: 'vyom-notification',
    storageBucket: 'vyom-notification.firebasestorage.app',
    iosBundleId: 'com.example.vyom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu4B7asXaYNaxUF4qm8jS313SzvTL_-oE',
    appId: '1:367467653808:web:6ad1fb2fbe5b42f3046975',
    messagingSenderId: '367467653808',
    projectId: 'vyom-notification',
    authDomain: 'vyom-notification.firebaseapp.com',
    storageBucket: 'vyom-notification.firebasestorage.app',
    measurementId: 'G-F9L23V4HXE',
  );
}
